// swift-tools-version:5.9
import PackageDescription

// Root SwiftPM package for VideoDownloader.
//
// Unit 1 of the build: the pure-logic library `VideoDownloaderCore`
// (macOS 14+, NO external dependencies) plus its XCTest test target.
// The macOS app shell (unit 2) lives under App/ and is generated by
// XcodeGen; it depends on the `VideoDownloaderCore` product declared here.
//
// The test target loads its JSON fixtures directly from disk via `#filePath`
// (see the Probe phase), NOT via `Bundle.module`, so the `Fixtures/` folder is
// `exclude`d below to silence SwiftPM's "unhandled files" warning.
let package = Package(
    name: "VideoDownloaderCore",
    platforms: [
        .macOS(.v14)
    ],
    products: [
        .library(
            name: "VideoDownloaderCore",
            targets: ["VideoDownloaderCore"]
        )
    ],
    targets: [
        .target(
            name: "VideoDownloaderCore",
            path: "Sources/VideoDownloaderCore"
        ),
        .testTarget(
            name: "VideoDownloaderCoreTests",
            dependencies: ["VideoDownloaderCore"],
            path: "Tests/VideoDownloaderCoreTests",
            exclude: ["Fixtures"]
        )
    ]
)
